name: auc_bias_syn
dependencies:
  - python=3.10.12
  - jupyter
  - pip
  - pip:
    - matplotlib==3.7.1
    - netcal==1.3.5
    - numpy==1.25.2
    - pandas==1.5.3
    - plotly==5.15.0
    - scipy==1.11.4
    - scikit-learn==1.3.2
    - tqdm==4.66.2
    - kaleido==0.2.1  

